spring:
  profiles:
    avtive:  prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306:3306/zipcartdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zipcartadmin
    password: adminpass123

    jpa:
      hibernate:
        ddl-auto: update