version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: zipcart-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: zipcartdb
      MYSQL_USER: zipcartuser
      MYSQL_PASSWORD: userpass123
    ports:
      - "3307:3306" # expose MySQL to host
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
