name: Auto Merge Testing → Staging

on:
  workflow_run:
    workflows: ["CI - Backend & Frontend Tests"]
    types:
      - completed
    branches: 
        - testing

permissions:
  contents: write
  actions: write

jobs:
  merge:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'testing' &&
      github.event.workflow_run.event != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: staging
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Merge testing into staging
        run: |
          git fetch origin
          git checkout staging
          git pull origin staging
          git merge origin/testing --no-edit
          git push origin staging

