name: Develop Branch Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  run-tests:
    uses: ./.github/workflows/unit-tests.yml

  publish-results:
    needs: run-tests
    uses: ./.github/workflows/publish-test-results.yml
