name: Publish Results

on:
  workflow_call:

permissions:
  contents: read
  checks: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Download Backend Results
        uses: actions/download-artifact@v4
        with:
          name: backend-test-results
          path: reports/backend

      - name: Download Frontend Results
        uses: actions/download-artifact@v4
        with:
          name: frontend-test-results
          path: reports/frontend

      - name: Publish JUnit Report
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: "reports/**/*.xml"
          detailed_summary: true
          include_passed: true