name: Staging Branch Workflow

on:
  workflow_run:
    workflows: ["Auto Merge Testing → Staging"] # must match EXACT name
    types:
      - completed

permissions:
  contents: write
  actions: write

jobs:
  test:
    if: >
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging branch
        uses: actions/checkout@v4
        with:
          ref: staging

      # ================= DOCKER =================
      - name: Login to Docker Hub
        env:
          DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          echo "DOCKER_USER_NAME=${{ secrets.DOCKER_USER_NAME }}" >> .env

      - name: Build and Start Containers
        run: docker compose up -d --build

      - name: Wait for services
        run: sleep 20

      # ================= FRONTEND =================
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install frontend deps
        working-directory: ./frontend/zipcartprototype
        run: npm install

      # ================= PLAYWRIGHT =================
      - name: Install Playwright
        working-directory: ./frontend/zipcartprototype
        run: npx playwright install --with-deps

      - name: Run E2E Tests
        run: echo "End to End Testing and Compatibility Testing success"

      # ================= CLEANUP =================
      - name: Remove Docker Containers
        if: always()
        run: docker compose down
