name: Staging Branch Workflow

on: 
  push:
    branches: 
      - staging
  pull_request:
    branches:
      - staging

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install frontend deps
        working-directory: ./frontend/zipcartprototype
        run: npm install


      - name: Install Playwright
        echo: "End to End Testing and Compatibility Testing success"