name: Testing Branch Workflow

on:
  push:
    branches:
      - main

  workflow_run:
    workflows: ["CI - Backend & Frontend Tests"]
    types:
      - completed

  pull_request:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug file structure
        run: ls -R

      - name: Node Installation
        uses: actions/setup-node@v4
        with:
          node-version: "24"

  postman-newman-action:
    name: Run Postman Newman GitHub Actions
    runs-on: ubuntu-latest

    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests
        run: newman run ./collections/zipcart_collection
